# Generated by Django 6.0.3 on 2026-05-23 15:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0008_remove_pet_foto_pet_foto_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoAdocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('animal_interesse', models.CharField(blank=True, max_length=100, null=True)),
                ('mensagem', models.TextField(blank=True, null=True)),
                ('data_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('nova', 'Nova'), ('em_analise', 'Em Análise'), ('respondida', 'Respondida'), ('recusada', 'Recusada')], default='nova', max_length=20)),
            ],
            options={
                'verbose_name': 'Solicitação de Adoção',
                'verbose_name_plural': 'Solicitações de Adoção',
            },
        ),
    ]
