# Generated by Django 6.0.3 on 2026-10-07 01:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0009_solicitacaoadocao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interessado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(blank=True, help_text='000.000.000-00', max_length=14, null=True, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('tipo_residencia', models.CharField(choices=[('apartamento', 'Apartamento'), ('casa', 'Casa')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Interesse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_interesse', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em análise'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado')], default='pendente', max_length=30)),
                ('interessado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gatos.interessado')),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada'), ('pendente', 'pendente')], default='pendente', max_length=30)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='adocao',
            name='adotante',
        ),
        migrations.DeleteModel(
            name='SolicitacaoAdocao',
        ),
        migrations.AlterModelOptions(
            name='adocao',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pet',
            options={},
        ),
        migrations.RemoveField(
            model_name='adocao',
            name='pet',
        ),
        migrations.AlterField(
            model_name='pet',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('em_analise', 'Em análise'), ('adotado', 'Adotado')], default='disponivel', max_length=20),
        ),
        migrations.AddField(
            model_name='interesse',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gatos.pet'),
        ),
        migrations.AddField(
            model_name='adocao',
            name='interesse',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gatos.interesse'),
        ),
        migrations.AddField(
            model_name='visita',
            name='interesse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gatos.interesse'),
        ),
        migrations.DeleteModel(
            name='Adotante',
        ),
    ]
