# Generated by Django 6.0.3 on 2026-10-07 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0010_interessado_interesse_visita_remove_adocao_adotante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interesse',
            name='mensagem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='status',
            field=models.CharField(choices=[('agendada', 'Agendada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada'), ('pendente', 'Pendente')], default='pendente', max_length=30),
        ),
    ]
