# Generated by Django 6.0.3 on 2026-10-07 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0011_interesse_mensagem_alter_visita_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='foto_url',
            new_name='foto',
        ),
    ]
